[RUN]
vocabulary = Vocabulary/ORBvoc.txt
calibration = em/run/settings/calibration_sim_rgbd.yaml
record = em/run/videos/datasets/sim/XXX
association = em/run/videos/datasets/sim/XXX/associations.txt
logs = em/run/videos/datasets/sim/XXX/logs

patient = true 
encoder = true
viewer = false

[PATIENT]
folder = em/run/centerline_frames/sim

[ENCODER]
sim_encoder = em/run/videos/datasets/sim/XXX/ca_data.csv

[PRIOR_WEIGHTS]
wT_gba =  10000.0
wT_lba =  1000.0
; wT_moba = 0.0
w_encoder = 1000.0
wx = 10.0
wy = 10.0
wz = 10.0
wroll = 1.0
wpitch = 1.0
wyaw = 1.0

[CBF]
distanceThreshold = 0.05 ; [m]
barrierWeight = 1.0